[ZEPPELIN-2155] Flaky test: NotebookTest -   NotebookTest.testPublicPrivateNewNote:11…
### What is this PR for?
 - Just give some static name to note say "1111" so it is always the first note.
    So, this fixes `NotebookTest.testPublicPrivateNewNote:1173 expected:<2C[B7YJQ16]> but was:<2C[A45Z6X7]>`

 - Set ConfVars.ZEPPELIN_NOTEBOOK_PUBLIC.getVarName() to "true", just in case any test fails, this should be reset to normal
    This fixes `NotebookTest.testAuthorizationRoles:759 expected:<false> but was:<true>`

### What type of PR is it?
[Bug Fix]

### What is the Jira issue?
* [https://issues.apache.org/jira/browse/ZEPPELIN-2155](https://issues.apache.org/jira/browse/ZEPPELIN-2155)

### How should this be tested?
CI should not fail with  `NotebookTest.testPublicPrivateNewNote:1173 expected:<2C[B7YJQ16]> but was:<2C[A45Z6X7]>` and  `NotebookTest.testAuthorizationRoles:759 expected:<false> but was:<true>`

Author: Prabhjyot Singh <prabhjyotsingh@gmail.com>

Closes #2070 from prabhjyotsingh/ZEPPELIN-2155 and squashes the following commits:

64e914d [Prabhjyot Singh] use contains instead of guessing the position, which in future may break.
3ca9c7b [Prabhjyot Singh] Merge remote-tracking branch 'origin/master' into ZEPPELIN-2155
0d1ebaf [Prabhjyot Singh] fix for   NotebookTest.testAuthorizationRoles:759 expected:<false> but was:<true>
9a5be5b [Prabhjyot Singh] Flaky test: NotebookTest -   NotebookTest.testPublicPrivateNewNote:1173 expected:<2C[B7YJQ16]> but was:<2C[A45Z6X7]>