[ZEPPELIN-6195] Fix Selenium tests by switching from Chrome to Firefox and upgrading outdated Spark
### What is this PR for?
 The `test-selenium-with-spark-module-for-spark-3-4` job in GitHub Actions was consistently failing with the error:
  ```bash
 from unknown command: 'Runtime.evaluate' wasn't found
 ```

 This issue was caused by ChromeDriver not recognizing the `Runtime.evaluate` command.
To resolve it, the browser used in the test was switched from Chrome to Firefox.

During the migration to Firefox, another issue occurred:
```bash
Unable to download from https://dlcdn.apache.org/spark/spark-3.4.2/spark-3.4.2-bin-hadoop3.tgz
java.io.FileNotFoundException: https://dlcdn.apache.org/spark/spark-3.4.2/spark-3.4.2-bin-hadoop3.tgz
```
This was due to the Spark 3.4.2 binaries no longer being available from the Apache mirror.
The test environment was therefore updated to use Spark 3.5.6, which resolved the download problem.

Summary of changes:
- Switched Selenium tests from Chrome to Firefox (non-snap) using geckodriver.
- Updated Spark version in the test environment from 3.4.2 to 3.5.6 to fix missing binary downloads.

Before: test-selenium-with-spark-module-for-spark-3-4 (Chrome, Spark 3.4.2)
After: test-selenium-with-spark-module-for-spark-3-5 (Firefox, Spark 3.5.6)

### What type of PR is it?
Bug Fix

### Todos
* [x] - Verified that other integration tests (if any) are not affected
* [x] - Confirmed long-term compatibility with the Chrome for Testing approach

### What is the Jira issue?
* Jira: https://issues.apache.org/jira/browse/ZEPPELIN-6195

### How should this be tested?
- Run the `test-selenium-with-spark-module-for-spark-3-4` job in GitHub Actions.
- Verify that `AuthenticationIT` and any other affected Selenium tests pass without encountering `Runtime.evaluate` errors.

### Screenshots (if appropriate)
N/A

### Questions:
* Does the license files need to update? No.
* Is there breaking changes for older versions? No.
* Does this needs documentation? No.

Closes #4941 from ParkGyeongTae/fix-selenium-runtime-evaluate-error.

Signed-off-by: Philipp Dallig <philipp.dallig@gmail.com>
(cherry picked from commit 8ec487f12bd0038ba311c3a56ce2db8b2c161f8d)
Signed-off-by: Philipp Dallig <philipp.dallig@gmail.com>