[ZEPPELIN-6370] Upgrade playwright and change the method of installing Playwright browsers
### What is this PR for?
https://github.com/apache/zeppelin/pull/5107
https://github.com/apache/zeppelin/actions/runs/18662031473/job/53204596550?pr=5107

In the Playwright E2E tests of the above bump PR, the following issue occurred:
```
Error: browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/webkit-2215/pw_run.sh
```

This issue seems to be caused by the Playwright browser installation step being version-locked in `zeppelin-web-angular/pom.xml`'s playwright-install execution.

Instead of managing it in `pom.xml`, it would be better to add it to the `postinstall` script in `zeppelin-web-angular/package.json`, so that Playwright browsers are automatically installed when running `npm install`, either in CI and on a local environment. This PR addresses that change.

61ff629c48f5f0cc552fa8a9b87d3e665b8601ea

Including the CI caching procedure as above, it seems optimized as previous approach(pom.xml).

### What type of PR is it?
Improvement

### Todos

### What is the Jira issue?
ZEPPELIN-6370

### How should this be tested?

### Screenshots (if appropriate)

### Questions:
* Does the license files need to update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No


Closes #5108 from dididy/e2e/upgrade-playwright.

Signed-off-by: ChanHo Lee <chanholee@apache.org>