[MINOR] Resolve bower dependency conflict, hang (zeppelin-web)
Due to angular dependency conflict, `bower install` command doesn't proceed further. It causes the whole build fail. (even in local)

```
62 silly postinstall zeppelin-web0.0.0 /Users/jl/local/src/g/zeppelin/zeppelin-web/zeppelin-web-cca93801
63 info lifecycle zeppelin-web0.0.0~postinstall: zeppelin-web0.0.0
64 verbose lifecycle zeppelin-web0.0.0~postinstall: unsafe-perm in lifecycle true
65 verbose lifecycle zeppelin-web0.0.0~postinstall: PATH: /Users/jl/local/src/g/zeppelin/zeppelin-web/node/node_modules/npm/bin/node-gyp-bin:/Users/j
l/local/src/g/zeppelin/zeppelin-web/node_modules/.bin:/Users/jl/local/src/g/zeppelin/zeppelin-web/node:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:
66 verbose lifecycle zeppelin-web0.0.0~postinstall: CWD: /Users/jl/local/src/g/zeppelin/zeppelin-web
67 silly lifecycle zeppelin-web0.0.0~postinstall: Args: [ '-c', 'bower install --silent' ]
68 silly lifecycle zeppelin-web0.0.0~postinstall: Returned: code: 1  signal: null
69 info lifecycle zeppelin-web0.0.0~postinstall: Failed to exec postinstall script
70 verbose stack Error: zeppelin-web0.0.0 postinstall: `bower install --silent`
70 verbose stack Exit status 1
70 verbose stack     at EventEmitter.<anonymous> (/Users/jl/local/src/g/zeppelin/zeppelin-web/node/node_modules/npm/lib/utils/lifecycle.js:255:16)
70 verbose stack     at emitTwo (events.js:106:13)
70 verbose stack     at EventEmitter.emit (events.js:191:7)
70 verbose stack     at ChildProcess.<anonymous> (/Users/jl/local/src/g/zeppelin/zeppelin-web/node/node_modules/npm/lib/utils/spawn.js:40:14)
70 verbose stack     at emitTwo (events.js:106:13)
70 verbose stack     at ChildProcess.emit (events.js:191:7)
70 verbose stack     at maybeClose (internal/child_process.js:877:16)
70 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
71 verbose pkgid zeppelin-web0.0.0
72 verbose cwd /Users/jl/local/src/g/zeppelin/zeppelin-web
73 error Darwin 16.1.0
74 error argv "/Users/jl/local/src/g/zeppelin/zeppelin-web/node/node" "/Users/jl/local/src/g/zeppelin/zeppelin-web/node/node_modules/npm/bin/npm-cli.
js" "install"
75 error node v6.9.1
76 error npm  v3.10.8
77 error code ELIFECYCLE
78 error zeppelin-web0.0.0 postinstall: `bower install --silent`
78 error Exit status 1
79 error Failed at the zeppelin-web0.0.0 postinstall script 'bower install --silent'.
79 error Make sure you have the latest version of node.js and npm installed.
79 error If you do, this is most likely a problem with the zeppelin-web package,
79 error not with npm itself.
79 error Tell the author that this fails on your system:
79 error     bower install --silent
79 error You can get information on how to open an issue for this project with:
79 error     npm bugs zeppelin-web
79 error Or if that isn't available, you can get their info via:
79 error     npm owner ls zeppelin-web
79 error There is likely additional logging output above.
80 verbose exit [ 1, true ]
```

you can get this `resolutions` field by executing `bower install --force`

```
"resolutions": {
    "angular": ">=1.2.15 <1.6"
  }
```

but we are using angular 1.5.0+ the resolution will cause errors like

```
[INFO]  undefined
       ERROR: 'Error: [$injector:unpr] Unknown provider: $$forceReflowProvider <- $$forceReflow <- $$animateQueue <- $animate <- $compile <- $$animateQueue
[INFO] http://errors.angularjs.org/1.4.3/$injector/unpr?p0=%24%24forceReflowProvider%20%3C-%20%24%24forceReflow%20%3C-%20%24%24animateQueue%20%3C-%20%24animate%20%3C-%20%24compile%20%3C-%20%24%24animateQueue

...
[INFO] PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 69 of 69 (34 FAILED) (0.236 secs / 0.269 secs)
[INFO] Warning: Task "karma:unit" failed. Use --force to continue.
```

So we need to specify 1.5.0 as the min angular version

[Bug Fix | Hot Fix]

* [x] - Task

Minor

CI will do that :)

* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

Author: 1ambda <1amb4a@gmail.com>

Closes #1725 from 1ambda/hotfix/resolve-bower-hangs and squashes the following commits:

533c5a3 [1ambda] fix: Use 1.5.0 min angular version
2b3d52d [1ambda] fix: Resolve bower install hangs

(cherry picked from commit ba50d49485972f6405d0d4a5d7f45a21cd9a95ff)
Signed-off-by: Lee moon soo <moon@apache.org>