[ZEPPELIN-941] jsoup NoSuchMethodError in ZeppelinRDisplay.scala
### What is this PR for?
Since version 1.8.2 of jsoup, org.jsoup.select.Elements class no longer has "get(int index)" method. It contradicts to <jsoup.version>1.8.2</jsoup.version> written in scala/pom.xml. Currently %r scripts fail with "java.lang.NoSuchMethodError: org.jsoup.select.Elements.get(I)Lorg/jsoup/nodes/Element;"

This PR changes obsolete get(0) method to more universal and logically equivalent first() method, removing error message and removing 1.8.1 restriction to jsoup library (at least in ZeppelinRDisplay part of zeppelin).

### What type of PR is it?
Bug Fix

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-941

### How should this be tested?
Execute R-Tutorial Notebook in default installation of zeppelin and confirm that you can see output.

### Questions:
It shouldn't break older versions.

Author: Andrey Oskin <a.oskin@corp.mail.ru>

Closes #949 from Arkoniak/rdisplay_jsoup_fix and squashes the following commits:

3d05400 [Andrey Oskin] jsoup get(0) to first()