[ZEPPELIN-6316] Fix broken tests caused by field name change
### What is this PR for?
After a field name change in `NewNoteRequest`, several tests are failing.

```
Error: Failures:
Error: NotebookRestApiTest.testCreateNote:555->lambda$testCreateNote$17:557 expected: <test1> but was: <Untitled Note>
Error: ZeppelinRestApiTest.testCloneNote:440->lambda$testCloneNote$8:443 Compare note names ==> expected: <clone Note Name> but was: <Cloned Note_2M6SWJ8WV>
Error: ZeppelinRestApiTest.testNoteCreateWithName:159->testNoteCreate:235->lambda$testNoteCreate$2:245 compare note name ==> expected: <Test note name> but was: <Untitled Note>
Error: ZeppelinRestApiTest.testNoteCreateWithParagraphs:181 test note create method:
```
Related Issue: #5055 


### What type of PR is it?
Fixing broken tests

### What is the Jira issue?
[ZEPPELIN-6316](https://issues.apache.org/jira/browse/ZEPPELIN-6316)

### How should this be tested?
- Check if tests success in `core-modules` job.
  - `NotebookRestApiTest.testCreateNote`
  - `ZeppelinRestApiTest.testCloneNote`
  - `ZeppelinRestApiTest.testNoteCreateWithName`
  - `ZeppelinRestApiTest.testNoteCreateWithParagraphs`

### Questions:
* Does the license files need to update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No


Closes #5066 from tbonelee/fix-tests.

Signed-off-by: ParkGyeongTae <gyeongtae@apache.org>