[ZEPPELIN-1883] Can't import spark submitted packages in PySpark
### What is this PR for?

Fixed importing packages in pyspack requested by `SPARK_SUBMIT_OPTION`

### What type of PR is it?
[Bug Fix]

### Todos

Nothing

### What is the Jira issue?

[ZEPPELIN-1883](https://issues.apache.org/jira/browse/ZEPPELIN-1883)

### How should this be tested?

0. Download Apache Spark 1.6.2 (since it's the most recent for pyspark-cassandra)

1. Set `SPARK_HOME` and `SPARK_SUBMIT_OPTION` in `conf/zeppelin-env.sh` like

```sh
export SPARK_HOME="~/github/apache-spark/1.6.2-bin-hadoop2.6"
export SPARK_SUBMIT_OPTIONS="--packages com.datastax.spark:spark-cassandra-connector_2.10:1.6.2,TargetHolding:pyspark-cassandra:0.3.5 --exclude-packages org.slf4j:slf4j-api"
```

2. Check before that you can run `spark-submit` or not

```
./bin/spark-submit --packages com.datastax.spark:spark-cassandra-connector_2.10:1.6.2,TargetHolding:pyspark-cassandra:0.3.5 --exclude-packages org.slf4j:slf4j-api --class org.apache.spark.examples.SparkPi lib/spark-examples-1.6.2-hadoop2.6.0.jar
```

3. Test whether submitted packages can be import or not

```
%pyspark

import pyspark_cassandra
```

### Screenshots (if appropriate)

```
import pyspark_cassandra

Traceback (most recent call last):
  File "/var/folders/lr/8g9y625n5j39rz6qhkg8s6640000gn/T/zeppelin_pyspark-5266742863961917074.py", line 267, in <module>
    raise Exception(traceback.format_exc())
Exception: Traceback (most recent call last):
  File "/var/folders/lr/8g9y625n5j39rz6qhkg8s6640000gn/T/zeppelin_pyspark-5266742863961917074.py", line 265, in <module>
    exec(code)
  File "<stdin>", line 1, in <module>
ImportError: No module named pyspark_cassandra
```

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

Author: 1ambda <1amb4a@gmail.com>

Closes #1831 from 1ambda/ZEPPELIN-1883/cant-import-submitted-packages-in-pyspark and squashes the following commits:

585d48a [1ambda] Use spark.jars instead of classpath
f76d2c8 [1ambda] fix: Do not extend PYTHONPATH in yarn-client
c735bd5 [1ambda] fix: Import spark submit packages in pyspark

(cherry picked from commit cb8e4187029fdd7b892d84f23efd51acaed65f78)
Signed-off-by: Lee moon soo <moon@apache.org>