[ZEPPELIN-2166] HeliumBundleFactoty can't transfile imported es6+
### What is this PR for?

Currently, we don't use any preset. This cause error messages like
when a helium package imports another packages which include es6+ syntax.

```
SyntaxError: Unexpected token import
    at helium.service.js:36
    at angular.js:10973
    at processQueue (angular.js:15552)
    at angular.js:15568
    at Scope.$eval (angular.js:16820)
    at Scope.$digest (angular.js:16636)
    at Scope.$apply (angular.js:16928)
    at done (angular.js:11266)
    at completeRequest (angular.js:11464)
    at XMLHttpRequest.requestLoaded (angular.js:11405)
```

- https://github.com/1ambda/zeppelin-advanced-transformation/blob/master/examples/example-highcharts-columnrange/index.js#L3
- https://github.com/1ambda/zeppelin-advanced-transformation/blob/master/index.js#L11

### What type of PR is it?
[Improvement]

### Todos
* [x] - Install required NPM packages
* [x] - fix babel configuration

### What is the Jira issue?

[ZEPPELIN-2166](https://issues.apache.org/jira/browse/ZEPPELIN-2166)

### How should this be tested?

- Should be able to bundle existing helium vis
- Should be able to bundle https://github.com/1ambda/zeppelin-advanced-transformation/tree/master/examples/example-highcharts-columnrange

### Screenshots (if appropriate)

NONE

### Questions:
* Does the licenses files need update? - NONE
* Is there breaking changes for older versions? - NONE
* Does this needs documentation? - NONE

Author: 1ambda <1amb4a@gmail.com>

Closes #2071 from 1ambda/ZEPPELIN-2166/fix-webpack-config-for-es6 and squashes the following commits:

40f6b51 [1ambda] fix: Update babel configuration