ZEPPELIN-1224: Fix typo in method name
### What is this PR for?
Get  the correct method to invoke, for autocompletion

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1224

### How should this be tested?
Try to get the auto complete suggestion.(`cmd + .`)
We should not get `NoSuchMethodError` and suggestions should be listed rightly

### Screenshots (if appropriate)
NA

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

Author: Karup <karuppayya@outlook.com>

Closes #1214 from karup1990/ZEPPELIN-1224 and squashes the following commits:

5d68984 [Karup] Fix variable names
cd3df44 [Karup] Fix typo in method name

(cherry picked from commit 73d99b880634809d615a063911573cb68b5d4864)
Signed-off-by: Lee moon soo <moon@apache.org>