[ZEPPELIN-3939] Spark 2.4 uses a more recent commons-lang3 than Zeppelin-0.8
### What is this PR for?
`Zeppelin-0.8.1` and `Zeppelin-0.8.2` cannot fully support Spark 2.4 if `commons-lang3` has incompaitble version from the one in Spark 2.4. The branch-0.9 (master) has already been updated to `3.7`, however the branch-0.8 hasn't done these changes.
By updating the version from `3.4` to `3.7` we resolve the issue that I have reported on Jira regarding reading `CSV` and `JSON` files in Spark 2.4.x.

Next release of `Zeppelin-0.8.x` can fully support Spark 2.4 without waiting for `Zeppelin 0.9.x`.

### What type of PR is it?
[Bug Fix]

### What is the Jira issue?
https://issues.apache.org/jira/projects/ZEPPELIN/issues/ZEPPELIN-3939

### How should this be tested?
* First time? Setup Travis CI:
Done
* Outline any manual steps to test the PR here.
I have tested reading `CSV` and `JSON` in `Zeppelin-0.8.0` (released), `Zeppelin-0.8.1` (released), and `Zeppelin-0.8.2` (not released yet) by pointing SPARK_HOME to spark-2.4.0 and they all failed same as the Jira issue.
```
java.io.InvalidClassException: org.apache.commons.lang3.time.FastDateParser; local class incompatible
```

After updating `common-lang3` to `3.7`, Zeppelin-0.8.2 reads the `CSV` and `JSON` files in spark-2.4.0 without any issue.

This has happened before and the solution was to update `commons-lang3` to appropriate version used in Apache Spark:
https://github.com/apache/zeppelin/commit/88a905caf2043d12a85462940c451b424d218dba

### Questions:
* Does the licenses files need update? Yes
* Is there breaking changes for older versions? No
* Does this needs documentation? No

Author: Maziyar Panahi <maziyar.panahi@iscpif.fr>

Closes #3290 from maziyarpanahi/branch-0.8 and squashes the following commits:

0709f5b47 [Maziyar Panahi] Add spark csv and json tests
9db542668 [Maziyar Panahi] Merge branch 'branch-0.8' of https://github.com/multivacplatform/zeppelin into branch-0.8
d59f27447 [Maziyar Panahi] Update commons-lang3 to fully support Spark 2.4
2b531755b [Maziyar Panahi] Update commons-lang3 to fully support Spark 2.4