[ZEPPELIN-3810] Support Spark 2.4
Spark 2.4 changed it's Scala version from 2.11.8 to 2.11.12 (see SPARK-24418).

There are two problems for this upgrade at Zeppelin side:

1.. Some methods that are used in private by reflection, for instance, `loopPostInit` became inaccessible.

See:
 - https://github.com/scala/scala/blob/v2.11.8/src/repl/scala/tools/nsc/interpreter/ILoop.scala
 - https://github.com/scala/scala/blob/v2.11.12/src/repl/scala/tools/nsc/interpreter/ILoop.scala

To work around this, I manually ported `loopPostInit` at 2.11.8 to retain the behaviour. Some functions that are commonly existing at both Scala 2.11.8 and Scala 2.11.12 are used inside of the new `loopPostInit` by reflection.

2.. Upgrade from 2.11.8 to 2.11.12 requires `jline.version` upgrade. Otherwise, we will hit:
```
Caused by: java.lang.NoSuchMethodError:
jline.console.completer.CandidateListCompletionHandler.setPrintSpaceAfterFullCompletion(Z)V
  at scala.tools.nsc.interpreter.jline.JLineConsoleReader.initCompletion(JLineReader.scala:139)
```

To work around this, I tweaked this by upgrading jline from `2.12.1` to `2.14.3`.

[Improvement]

* [x] - Wait until Spark 2.4.0 is officially released.

* https://issues.apache.org/jira/browse/ZEPPELIN-3810

Verified manually against Spark 2.4.0 RC3

* Does the licenses files need update? Yes
* Is there breaking changes for older versions? No
* Does this needs documentation? No

Author: hyukjinkwon <gurwls223@apache.org>
Author: Hyukjin Kwon <gurwls223@apache.org>
Author: Jeff Zhang <zjffdu@gmail.com>

Closes #3206 from HyukjinKwon/ZEPPELIN-3810 and squashes the following commits:

c2456c949 [Hyukjin Kwon] Py4J 0.10.6 to 0.10.7
573f07d2d [Jeff Zhang] add test for spark 2.4 (#1)
9ac1797a7 [hyukjinkwon] Support Spark 2.4

(cherry picked from commit 4f73272c006b3767ad40686aa5876ac5fbf57928)