[ZEPPELIN-5144] Jupyter conda python packages
### What is this PR for?
This PR includes:
 - checkKernelPrerequisite does not fail if the Python packages are installed with conda
 - Fixes the following Python bug with an additional if check
```
ERROR [2020-11-24 10:50:23,995] ({grpc-default-executor-2} JupyterKernelClient.java[onError]:231) - Fail to call IPython grpc
io.grpc.StatusRuntimeException: UNKNOWN: Exception iterating responses: 'payload'
```

### What type of PR is it?
 - Bug Fix

### Todos
* [x] - Test with CI

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-5144

### How should this be tested?
* GitHub-Action: https://github.com/Reamer/zeppelin/runs/1479335046

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

Author: Philipp Dallig <philipp.dallig@gmail.com>

Closes #3982 from Reamer/jupyter_conda and squashes the following commits:

8cf446429 [Philipp Dallig] Check if payload is available
2f6838a6f [Philipp Dallig] Allow installation of Python requirements with conda
16b52c2f6 [Philipp Dallig] Some style changes

(cherry picked from commit e5b6850667ac0f67bef9e1d0d410f37ded2e01ed)
Signed-off-by: Philipp Dallig <philipp.dallig@gmail.com>