[ZEPPELIN-185] ZeppelinContext methods like z.show are not working with DataFrame in pyspark
(opening a new PR to have a start history)

z.show() doesn’t seem to work properly in Python – I see the same error below: “AttributeError: 'DataFrame' object has no attribute '_get_object_id'"
#Python/PySpark – doesn’t work
rdd = sc.parallelize(["1","2","3"])
Data = Row('first')
df = sqlContext.createDataFrame(rdd.map(lambda d: Data(d)))
print df
print df.collect()
z.show(df)
AttributeError: 'DataFrame' object has no attribute ‘_get_object_id'

More generally, ZeppelinContext methods are not working with Python objects since Py4J would need to know how to serialize it

It turns out the error is caused by Py4J trying to auto convert the DataFrame, which fails since it can only do that for simple types.
Instead of getting conversion to work, the better approach is to pass along the inner java object instead. To do that we intercept the call on the python side with a wrapper object instead of letting Py4J handle it.
As per comment, adding container/dictionary methods to allow for string passing using ZeppelinContext

Author: Felix Cheung <felixcheung_m@hotmail.com>

Closes #178 from felixcheung/zpyspark and squashes the following commits:

ddc5bb2 [Felix Cheung] small fixes to python script
df6588a [Felix Cheung] [ZEPPELIN-185] ZeppelinContext methods like z.show are not working with DataFrame in pyspark It turns out the error is caused by Py4J trying to auto convert the DataFrame, which fails since it can only do that for simple types. Instead of getting conversion to work, the better approach is to pass along the inner java object instead. To do that we intercept the call on the python side with a wrapper object instead of letting Py4J handle it. As per comment, adding container/dictionary methods to allow for string passing using ZeppelinContext