[HOTFIX][ZEPPELIN-2011] Add lib/interpreter to classpath to fix interpreter installer
### What is this PR for?
Interpreter installation fail with `NoClassDefFoundError` error when zeppelin is built as distribution package. This PR fixes it by adding `lib/interpreter` to classpath.

### What type of PR is it?
Bug Fix | Hot Fix

### What is the Jira issue?
[ZEPPELIN-2011](https://issues.apache.org/jira/browse/ZEPPELIN-2011)

### How should this be tested?
1. Build distribution package
```
mvn clean package -DskipTests -pl zeppelin-interpreter,zeppelin-zengine,:zeppelin-display_2.10,:zeppelin-spark-dependencies_2.10,:zeppelin-spark_2.10,zeppelin-web,zeppelin-server,zeppelin-distribution -am -Pbuild-distr
```
2. Change working directory
```
$ cd zeppelin-distribution/target/zeppelin-0.8.0-SNAPSHOT/zeppelin-0.8.0-SNAPSHOT
```
3. Run `bin/install-interpreter.sh` and see if error is gone.

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

Author: Mina Lee <minalee@apache.org>

Closes #1943 from minahlee/ZEPPELIN-2011 and squashes the following commits:

ed3776d [Mina Lee] Add lib/interpreter to classpath

(cherry picked from commit 90735979aaf4b2f58fa34ed0ab1aeccc37cb56bd)
Signed-off-by: Mina Lee <minalee@apache.org>