ZEPPELIN-1270. Remove getting SQLContext from SparkSession.wrapped()
### What is this PR for?
SparkSession.wrapped is only for spark 2.0 preview, it is not supported in spark 2.0 release. So I think we can remove that piece of code. Otherwise we will get the following error in log which might be a little confusing.
```
08:05:44,946 - Thread(pool-2-thread-3) - (Utils.java:40) - org.apache.spark.sql.SparkSession.wrapped()
java.lang.NoSuchMethodException: org.apache.spark.sql.SparkSession.wrapped()
    at java.lang.Class.getMethod(Class.java:1786)
    at org.apache.zeppelin.spark.Utils.invokeMethod(Utils.java:38)
    at org.apache.zeppelin.spark.Utils.invokeMethod(Utils.java:33)
```

### What type of PR is it?
[Improvement]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-1270

### How should this be tested?
Check the log and the above error is gone.

### Screenshots (if appropriate)

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

Author: Jeff Zhang <zjffdu@apache.org>

Closes #1269 from zjffdu/ZEPPELIN-1270 and squashes the following commits:

a685e66 [Jeff Zhang] ZEPPELIN-1270. Remove getting SQLContext from SparkSession.wrapped()

(cherry picked from commit b6310ada120ec385d7e4e4264a69a238dd87d045)
Signed-off-by: Lee moon soo <moon@apache.org>