Initialize chart to null inside 'render()'
* Fixes ZEPPELIN-2253
* When pie chart's key(domain) is changed, this error is logged:
 'Uncaught TypeError: arcs[idx] is not a function at pie.js:358'
* Even if we change key and values, chart remains broken

* Fix: set this.chart to null, which inturn makes this.render to
intialize a new chart constructor