[ZEPPELIN-3698] Zeppelin stops working after a few days of uptime with RemoteEndpoint unavailable, outgoing connection not open
Notebooks suddenly show up empty (are not loading) and the logfile (apache-zeppelin-dev.log) shows the following error:
```
org.eclipse.jetty.websocket.api.WebSocketException: RemoteEndpoint unavailable, outgoing connection not open
at org.eclipse.jetty.websocket.common.WebSocketSession.getRemote(WebSocketSession.java:252)
at org.apache.zeppelin.socket.NotebookSocket.send(NotebookSocket.java:70)
...
```

It seems that checking the `WebSocketException` after `NotebookSocket.send` will solve this problem .

Bug Fix

* issue: https://issues.apache.org/jira/browse/ZEPPELIN-3698

* CI pass

* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

Author: egorklimov <klim.electronicmail@gmail.com>

Closes #3167 from egorklimov/ZEPPELIN-3698 and squashes the following commits:

29c2ae91e [egorklimov] Exceptions added

(cherry picked from commit 5c94d7550aa569361d5c5569004917ee9bd82c70)
Signed-off-by: Jeff Zhang <zjffdu@apache.org>